### ISSUE TITLE
Incompatible with 1.18.2

### ISSUE THREAD

**Issue by Boobies** [ChachyDev/lazy-language-loader#7]
While it's marked as 1.18.2-compatible on CurseForge, it crashes the game:

```
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3304 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.<init>(class_310.java:504)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method lazyLanguageLoader$$onReload(Ljava/lang/Iterable;)Ljava/lang/Iterable; in lazy-language-loader.mixin.json:optimizations.loading.MixinReloadableResourceManagerImpl from mod lazy-language-loader failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap lazy-language-loader-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 23 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.<init>(class_310.java:504)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.10.0-11-amd64
	Java Version: 17.0.2, Debian
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Debian
	Memory: 488759272 bytes (466 MiB) / 897581056 bytes (856 MiB) up to 1073741824 bytes (1024 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 4.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: GP104 [GeForce GTX 1070 Ti]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1b82
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 8927.06
	Virtual memory used (MB): 7515.79
	Swap memory total (MB): 954.00
	Swap memory used (MB): 891.22
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	Fabric Mods: 
		fabric: Fabric API 0.47.8+1.18.2
		fabric-api-base: Fabric API Base 0.4.3+d7c144a8d2
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.6+d7c144a8d2
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.1+2873dd57d2
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.11+3ac43d95d2
		fabric-command-api-v1: Fabric Command API (v1) 1.1.8+d7c144a8d2
		fabric-commands-v0: Fabric Commands (v0) 0.2.7+b4f4f6cdd2
		fabric-containers-v0: Fabric Containers (v0) 0.1.20+d7c144a8d2
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.0+d82b9392d2
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.10+3ac43d95d2
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.16+25407454d2
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.7+d7c144a8d2
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.18+d7c144a8d2
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.12+d7c144a8d2
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.12+d7c144a8d2
		fabric-item-api-v1: Fabric Item API (v1) 1.3.2+691a79b5d2
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.8+3ac43d95d2
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.11+54e5b2ecd2
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.9+b4f4f6cdd2
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.1+25407454d2
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.10+d7c144a8d2
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.2+d1027f7dd2
		fabric-models-v0: Fabric Models (v0) 0.3.5+d7c144a8d2
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.20+d882b915d2
		fabric-networking-v0: Fabric Networking (v0) 0.3.7+b4f4f6cdd2
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.1+d882b915d2
		fabric-particles-v1: Fabric Particles (v1) 0.2.11+526dc1acd2
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.5+55dca1a4d2
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.12+d882b915d2
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.16+d8c7b9aed2
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cdd2
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.6+d7c144a8d2
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.1+54e5b2ecd2
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cdd2
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+54e5b2ecd2
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.1+d1027f7dd2
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.16+55dca1a4d2
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.9+d882b915d2
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.13+d7c144a8d2
		fabric-textures-v0: Fabric Textures (v0) 1.0.11+3ac43d95d2
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.12+d882b915d2
		fabricloader: Fabric Loader 0.13.3
		java: OpenJDK 64-Bit Server VM 17
		lazy-language-loader: lazy-language-loader 0.2.6
		minecraft: Minecraft 1.18.2
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 460.91.03, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
#@!@# Game crashed! Crash report saved to: #@!@# /home/rooftopjoe/.local/share/multimc/instances/1.18.2/.minecraft/crash-reports/crash-2022-03-03_00.56.21-client.txt
Process exited with code 255.

```

**Comment by ChachyDev** [comment]
oops i'll unmark it and check this issue out in a few hours

**Comment by ChachyDev** [comment]
Fixed in https://github.com/ChachyDev/lazy-language-loader/commit/18bc591fa5f128504116db8f491924ced69f7be7, I'll close this once 0.3.0 has been released on all platforms.

**Comment by ChachyDev** [comment]
Released on all platforms:
https://www.curseforge.com/minecraft/mc-mods/lazy-language-loader/files/3672438
https://modrinth.com/mod/lazy-language-loader/version/0.3.0
https://github.com/ChachyDev/lazy-language-loader/releases/tag/0.3.0
